sudo: required

language: node_js

addons:
  ssh_known_hosts: 
   - demo.jetpad.net
   - jetpad.net
   - assange.fdi.ucm.es

cache:
  directories:
  - node_modules

node_js:
  node

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3


install:
  - npm rebuild node-sass
  - npm i

script:
  - npm run build:prod

after_success:
  - openssl aes-256-cbc -K $encrypted_e4cde9e990bb_key -iv $encrypted_e4cde9e990bb_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf .travis/secrets.tar --directory .travis 
  - chmod ugo+x .travis/deploy.sh
  - .travis/deploy.sh	

notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGxsb3B2JTNBbWF0cml4Lm9yZy8lMjFic2tzYVVMV21FVExtZnN0YXIlM0FtYXRyaXgub3Jn"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
